stx-puppet: add re-tries to workaround docker login failure
Add re-tries to workaround the follwoing docker login failure:
Error: docker login registry.local:9001 -u admin -p St8rlingX* returned 1 instead of one of [0]
Error: /Stage[main]/Platform::Kubernetes::Master::Init/Exec[login local
       registry]/returns: change from notrun to 0 failed: docker login
       registry.local:9001 -u admin -p St8rlingX* returned 1 instead of one of [0]

Partial-Bug: 1905380

Change-Id: Idcad1b2c8e751d9a189a102f449f55489368a8f0
Signed-off-by: Jackie Huang <jackie.huang@windriver.com>